#!/bin/bash
#!/data/data/com.termux/files/usr/bin/bash
echo " "
clear 
echo -e "\e[32;1m
_ _ _ _    _  _ _  _ _  _ 
| | | | __ |\/| |  |  \/  
|_|_| |    |  | |__| _/\_ #Wifite-Termux
"
echo " Author : mhmmd.ridwan"
echo " FB     : facebook.com/rdwn.xyz"
echo " Note   : Hanya berfungsi di processor snapdragon & sudah di root!"
echo -e "\e[31;1m"
PS3='Pilih > '
wimux=("Install Paket" "Monitor Mode ON" "Monitor Mode OFF" "Wifite2" "Tentang Wi-Mux" "Keluar")

select wim in "${wimux[@]}"
do
	case $wim in
		"Install Paket")
			cd $HOME
			pkg update -y
			pkg upgrade -y
			pkg install root-repo -y
			pkg install x11-repo -y
			pkg install unstable-repo -y
			pkg install git -y
			pkg install iw -y
			pkg install wireless-tools -y
			pkg install aircrack-ng -y
			git clone https://github.com/ripunk/wlan0mon.git
			git clone https://github.com/derv82/wifite2
			cd wlan0mon
			chmod +x monen mondis
			echo "#############################"
			echo "# Paket berhasil di Install #"
			echo "#############################"
			;;
		"Monitor Mode ON")
			cd $HOME
			cd wlan0mon
			sudo ./monen
			echo "######################"
			echo "# Monitor Mode Aktif #"
			echo "######################"
			;;
		"Monitor Mode OFF")
			cd $HOME
			cd wlan0mon
			sudo ./mondis
			echo "##########################"
			echo "# Monitor Mode Non-Aktif #"
			echo "##########################"
			;;
		"Wifite2")
			cd $HOME
			cd wifite2
			sudo python -i Wifite.py wlan0
			;;
		"Tentang Wi-Mux")
			echo "Wifite2 For Termux, Tools ini hanya untuk mempermudah dalam instalasi wifite2 dengan fitur monitor mode."
			;;
		"Keluar")
			break
			echo acdf | select wim in "${wimus[@]}"; do break; done
			;;
		*) echo "Input Salah > $REPLY"
		;;
	esac
done
clear
